# Basic set of initial stress tests to test overcloud before running complete set of benchmarks.
browbeat:
  cloud_name: openstack
  rerun: 1
  # Two types of rerun:
  # iteration reruns on the iteration
  # complete reruns after all workloads complete
  # rerun_type: complete
  rerun_type: iteration
ansible:
  hosts: ansible/hosts
  metadata_playbook: ansible/gather/stockpile.yml
  ssh_config: ansible/ssh-config
  container_cli: docker
elasticsearch:
  enabled: false
  host: 1.1.1.1
  port: 9200
  regather: false
  metadata_files:
    - name: hardware-metadata
      file: metadata/hardware-metadata.json
    - name: environment-metadata
      file: metadata/environment-metadata.json
    - name: software-metadata
      file: metadata/software-metadata.json
    - name: version
      file: metadata/version.json
grafana:
  enabled: false
  host: example.grafana.com
  port: 3000
  dashboards:
    - openstack-general-system-performance
perfkit:
  sleep_before: 0
  sleep_after: 0
  default:
    image: centos7
    machine_type: m1.small
    os_type: rhel
    openstack_image_username: centos
    openstack_floating_ip_pool: browbeat_public
    openstack_network: browbeat_private
    timing_measurements: runtimes
    ignore_package_requirements: true
rally:
  sleep_before: 5
  sleep_after: 5
  plugins:
    - glance: rally/rally-plugins/glance
    - neutron: rally/rally-plugins/neutron
    - netcreate-boot: rally/rally-plugins/netcreate-boot
    - workloads: rally/rally-plugins/workloads
shaker:
  server: 1.1.1.1
  port: 5555
  flavor: m1.small
  join_timeout: 600
  sleep_before: 0
  sleep_after: 0
  shaker_region: regionOne
  external_host: 2.2.2.2

workloads:
  - name: simple-plugins
    enabled: true
    type: rally
    concurrency:
      - 16
    times: 100
    scenarios:
      - name: netcreate-light-boot-ping
        enabled: true
        image_name: "cirros"
        flavor_name: "m1.xtiny"
        ext_net_id: "4f0960d7-373f-487f-8bbd-e4327c30adf2"
        file: rally/rally-plugins/netcreate-boot/netcreate_light_boot_fip_ping.yml
