#!/bin/bash

temp_dir=$(mktemp -d)


function get_num_of_ports {
    ports=$(sudo ovs-vsctl list-ports br-int |grep b_ > ${temp_dir}/${t_date}_ports)
    num=$(sudo cat ${temp_dir}/${t_date}_ports | wc -l)
    if [[ $num -gt 0 ]]; then echo $num; else echo 0; fi
}

function get_num_of_pflows {
    flows=$(sudo ovs-ofctl dump-flows br-int > ${temp_dir}/${t_date}_flows)
    num=$(sudo cat ${temp_dir}/${t_date}_flows | wc -l)
    if [[ $num -gt 0 ]]; then echo $num; else echo 0; fi
}

function print_summary {
    t_date=$(date +"%T")
    ports=$(get_num_of_ports)
    pflows=$(get_num_of_pflows)
    echo "${t_date},${ports},${pflows}"
}

while true; do 
    print_summary >> ${temp_dir}/res
    sleep 5
done
